### ISSUE TITLE
1.18.2 water despawn's below Y level 0

### ISSUE THREAD

**Issue by baconbits4** [Felicis/Water-Physics-Overhaul#24] opened 2023-06-20 05:11 UTC
i assume this is because caves and cliff lowered the depth limit any chance you could fix please and thank you 
It needs to be lowered to -65 so it never despawns

**Comment by djmrFunnyMan** [comment] 2023-06-20 12:22
duplicate of #4

**Closed** 2023-06-20 22:18 UTC
